import type {
  ApplicationStatus,
  JobCategory,
  WorkArrangement,
} from "@/lib/applications/constants";

/**
 * One fictional application, described by what it is rather than by dates.
 *
 * Every date in the demo is an offset in days from whatever "today" the builder
 * is given, so the workspace is as current in a year as it is this afternoon.
 * A seed therefore says *how long ago* something happened, never *when*.
 *
 * `path` is the statuses this application has held, oldest first, ending at the
 * one it is at now. The builder derives the current status, the status history,
 * `date_applied` and both timestamps from it, so a record cannot disagree with
 * its own history: there is only one place the truth is written.
 */
export type DemoSeed = {
  /** Stable, URL-safe, and unique. Demo ids are not UUIDs and never pretend to be. */
  id: string;
  company: string;
  /** The employer's real corporate domain, for the existing Logo.dev lookup. */
  domain: string | null;
  title: string;
  category: JobCategory;
  term: DemoWorkTerm;
  /** Omitted where the student never recorded one. */
  source?: string;
  path: [ApplicationStatus, ...ApplicationStatus[]];
  /** Days before "today" that the first event in `path` happened. */
  firstEventDaysAgo: number;
  /** Days between consecutive events. Defaults to five. */
  stepDays?: number;
  location?: string;
  arrangement?: WorkArrangement;
  salary?: string;
  duration?: string;
  url?: string;
  notes?: string;
  jobDescription?: string;
  /** A recorded commitment. Its due date is meaningless without it, so the two travel together. */
  nextAction?: { text: string; inDays: number };
  /** Days from today the posting closes. Only meaningful before submission. */
  deadlineInDays?: number;
  /**
   * Days before today that the student filed this one away.
   *
   * Absent on all but a handful of finished records, which is what a real
   * archive looks like. Archiving is not deletion: an archived application
   * keeps its whole history and stays part of the search analytics describe,
   * and it simply stops appearing on the surfaces about what is still in play.
   */
  archivedDaysAgo?: number;
};

export const DEMO_WORK_TERMS = [
  "Fall 2026",
  "Winter 2027",
  "Summer 2027",
] as const;

export type DemoWorkTerm = (typeof DEMO_WORK_TERMS)[number];

const TORONTO = "Toronto, ON";

/**
 * The sample search: a business student working three recruiting cycles at once.
 *
 * Fictional throughout. The employers are real organisations named so that a
 * student recognises the shape of the dataset immediately, but no application,
 * title, description, date or outcome here describes anything that happened,
 * and none of these employers has any connection to Interndex.
 *
 * Deliberately uneven. Several employers appear three or four times with
 * different roles, which is the case the whole product is designed around —
 * it is why the applications list and the pipeline board lead with the role and
 * put the employer underneath. And several records are close to empty, because
 * a tracker where every optional field is filled in is a tracker nobody
 * actually kept.
 */
export const DEMO_SEEDS: readonly DemoSeed[] = [
  // ---------------------------------------------------------------- Fall 2026
  {
    id: "deloitte-technology-consulting-w27",
    company: "Deloitte",
    domain: "deloitte.com",
    title: "Technology Consulting Intern",
    category: "Consulting",
    term: "Winter 2027",
    source: "Company website",
    path: ["Applied", "Screening", "Interview", "Offer"],
    firstEventDaysAgo: 52,
    stepDays: 9,
    location: TORONTO,
    arrangement: "Hybrid",
    salary: "$27/hour",
    duration: "4 months",
    notes:
      "Offer received after the second round. Asked for a week to decide — the TD offer is open until the end of the month and the RBC process is still running.",
    nextAction: { text: "Reply to the Deloitte offer", inDays: 1 },
  },
  {
    id: "ibm-business-technology-analyst-f26",
    company: "IBM",
    domain: "ibm.com",
    title: "Business Technology Analyst Intern",
    category: "Information Technology",
    term: "Fall 2026",
    source: "Referral",
    path: ["Applied", "Screening", "Interview", "Offer", "Accepted"],
    firstEventDaysAgo: 76,
    stepDays: 12,
    location: TORONTO,
    arrangement: "Hybrid",
    salary: "$26/hour",
    duration: "4 months",
    url: "https://www.example.com/careers/business-technology-analyst-intern",
    notes:
      "Referred by a classmate on their second term. Two rounds: a case discussion, then a conversation with the delivery lead. Accepted — this is the Fall term sorted.",
    jobDescription:
      "Work alongside a client delivery team to gather requirements, document current-state processes and help prepare the artefacts a transformation programme runs on. You will sit in workshops with business stakeholders, keep the requirements traceability matrix current, and prepare the weekly status pack for the programme steering committee.\n\nWhat you will do\n- Translate stakeholder conversations into written, reviewable requirements\n- Maintain process documentation as the current state is mapped\n- Prepare status reporting and track actions to closure\n- Support user acceptance testing and collate defects\n\nWhat we look for\n- Business, commerce or management information systems student\n- Comfortable writing clearly for a non-technical audience\n- Organised enough to run a workshop's actions without being chased",
  },
  {
    id: "rbc-business-analyst-f26",
    company: "RBC",
    domain: "rbc.com",
    title: "Business Analyst Intern",
    category: "Business Analysis",
    term: "Fall 2026",
    source: "University job board",
    path: ["Applied", "Screening", "Rejected"],
    firstEventDaysAgo: 70,
    stepDays: 11,
    location: TORONTO,
    arrangement: "Hybrid",
    notes: "Screening call went well. Told the team went with a returning intern.",
  },
  {
    id: "kpmg-risk-advisory-f26",
    company: "KPMG",
    domain: "kpmg.com",
    title: "Risk Advisory Intern",
    category: "Consulting",
    term: "Fall 2026",
    source: "LinkedIn",
    path: ["Applied", "Rejected"],
    firstEventDaysAgo: 68,
    stepDays: 14,
    location: TORONTO,
    // Rejected, read, and tidied away. Still part of the funnel.
    archivedDaysAgo: 41,
  },
  {
    id: "td-commercial-banking-f26",
    company: "TD",
    domain: "td.com",
    title: "Commercial Banking Intern",
    category: "Finance",
    term: "Fall 2026",
    source: "Company website",
    path: ["Applied", "Screening", "Interview"],
    firstEventDaysAgo: 40,
    stepDays: 10,
    location: TORONTO,
    arrangement: "On-site",
    notes: "Panel interview with two relationship managers. Waiting to hear.",
  },
  {
    id: "accenture-consulting-analyst-f26",
    company: "Accenture",
    domain: "accenture.com",
    title: "Consulting Analyst Intern",
    category: "Consulting",
    term: "Fall 2026",
    source: "LinkedIn",
    path: ["Applied"],
    firstEventDaysAgo: 63,
    location: TORONTO,
  },
  {
    id: "ey-internal-audit-f26",
    company: "EY",
    domain: "ey.com",
    title: "Internal Audit Intern",
    category: "Accounting",
    term: "Fall 2026",
    source: "University job board",
    path: ["Applied", "Screening", "Assessment", "Rejected"],
    firstEventDaysAgo: 74,
    stepDays: 9,
    location: "Ottawa, ON",
    arrangement: "Hybrid",
    notes: "Did the online assessment. No feedback given.",
    // Rejected, read, and tidied away. Still part of the funnel.
    archivedDaysAgo: 33,
  },
  {
    id: "bmo-capital-markets-operations-f26",
    company: "BMO",
    domain: "bmo.com",
    title: "Capital Markets Operations Intern",
    category: "Finance",
    term: "Fall 2026",
    source: "Networking event",
    path: ["Applied", "Screening"],
    firstEventDaysAgo: 30,
    stepDays: 9,
    location: TORONTO,
    arrangement: "On-site",
    nextAction: { text: "Send thank-you note to the BMO recruiter", inDays: 1 },
  },
  {
    id: "scotiabank-marketing-f26",
    company: "Scotiabank",
    domain: "scotiabank.com",
    title: "Marketing Intern",
    category: "Marketing",
    term: "Fall 2026",
    source: "LinkedIn",
    path: ["Applied"],
    firstEventDaysAgo: 58,
    location: TORONTO,
  },
  {
    id: "cibc-business-systems-analyst-f26",
    company: "CIBC",
    domain: "cibc.com",
    title: "Business Systems Analyst Intern",
    category: "Business Analysis",
    term: "Fall 2026",
    source: "Company website",
    path: ["Applied", "Screening", "Assessment"],
    firstEventDaysAgo: 33,
    stepDays: 10,
    location: TORONTO,
    arrangement: "Hybrid",
    nextAction: { text: "Finish the CIBC case assessment", inDays: 0 },
  },
  {
    id: "pwc-digital-transformation-f26",
    company: "PwC",
    domain: "pwc.com",
    title: "Digital Transformation Intern",
    category: "Consulting",
    term: "Fall 2026",
    source: "Recruiter",
    path: ["Applied", "Screening", "Withdrawn"],
    firstEventDaysAgo: 61,
    stepDays: 12,
    location: "Montréal, QC",
    notes: "Withdrew — the term dates clashed with the IBM offer.",
  },
  {
    id: "nbc-corporate-strategy-f26",
    company: "National Bank of Canada",
    domain: "nbc.ca",
    title: "Corporate Strategy Intern",
    category: "Strategy and Operations",
    term: "Fall 2026",
    source: "Referral",
    path: ["Applied", "Screening", "Interview", "Offer", "Withdrawn"],
    firstEventDaysAgo: 78,
    stepDays: 12,
    location: "Montréal, QC",
    arrangement: "Hybrid",
    salary: "$25/hour",
    duration: "4 months",
    notes:
      "Declined — took the IBM offer for the same term instead. Bilingual role; the interview was half in French, which was good practice.",
    // Finished and filed away. It still counts in the funnel, because reaching
    // an offer is part of what happened this cycle.
    archivedDaysAgo: 24,
  },
  {
    id: "telus-sales-operations-f26",
    company: "Telus",
    domain: "telus.com",
    title: "Sales Operations Intern",
    category: "Sales",
    term: "Fall 2026",
    source: "LinkedIn",
    path: ["Applied"],
    firstEventDaysAgo: 44,
    location: "Vancouver, BC",
    arrangement: "Remote",
  },
  {
    id: "loblaw-supply-chain-analyst-f26",
    company: "Loblaw",
    domain: "loblaw.ca",
    title: "Supply Chain Analyst Intern",
    category: "Strategy and Operations",
    term: "Fall 2026",
    source: "Company website",
    path: ["Applied", "Screening"],
    firstEventDaysAgo: 36,
    stepDays: 11,
    location: "Brampton, ON",
  },
  {
    id: "cgi-business-process-improvement-f26",
    company: "CGI",
    domain: "cgi.com",
    title: "Business Process Improvement Intern",
    category: "Consulting",
    term: "Fall 2026",
    source: "University job board",
    path: ["Applied"],
    firstEventDaysAgo: 51,
    location: "Ottawa, ON",
  },
  {
    id: "kpmg-change-management-f26",
    company: "KPMG",
    domain: "kpmg.com",
    title: "Change Management Intern",
    category: "Human Resources",
    term: "Fall 2026",
    path: ["Interested"],
    firstEventDaysAgo: 9,
    deadlineInDays: 5,
    location: TORONTO,
  },
  {
    id: "deloitte-strategy-operations-f26",
    company: "Deloitte",
    domain: "deloitte.com",
    title: "Strategy & Operations Intern",
    category: "Strategy and Operations",
    term: "Fall 2026",
    source: "Networking event",
    path: ["Applied", "Screening", "Interview", "Rejected"],
    firstEventDaysAgo: 66,
    stepDays: 10,
    location: TORONTO,
    arrangement: "Hybrid",
    notes: "Final round. Came down to two candidates.",
  },

  // -------------------------------------------------------------- Winter 2027
  {
    id: "rbc-commercial-banking-w27",
    company: "RBC",
    domain: "rbc.com",
    title: "Commercial Banking Intern",
    category: "Finance",
    term: "Winter 2027",
    source: "Company website",
    path: ["Applied", "Screening", "Interview"],
    firstEventDaysAgo: 34,
    stepDays: 10,
    location: TORONTO,
    arrangement: "Hybrid",
    salary: "$24–$26/hour",
    duration: "4 months",
    url: "https://www.example.com/careers/commercial-banking-intern-winter",
    notes:
      "Second round is a case: read a small business's statements and recommend a facility. Recruiter said to expect 45 minutes with two people from the team, and that they will ask why commercial rather than capital markets.",
    jobDescription:
      "Support a commercial banking team through the credit cycle for small and mid-sized business clients. You will help prepare credit reviews, keep client files current, and join client meetings alongside the relationship manager.\n\nWhat you will do\n- Prepare spreads and background for annual credit reviews\n- Draft sections of credit applications for the relationship manager's review\n- Keep client records and covenant tracking current\n- Attend client meetings and write the follow-up notes\n\nWhat we look for\n- Business or commerce student with an interest in credit\n- Comfortable reading a set of financial statements\n- Clear written communication; much of this role is writing",
    nextAction: {
      text: "Prepare for the RBC second-round case interview",
      inDays: -1,
    },
  },
  {
    id: "td-business-analyst-w27",
    company: "TD",
    domain: "td.com",
    title: "Business Analyst Intern",
    category: "Business Analysis",
    term: "Winter 2027",
    source: "Referral",
    path: ["Applied", "Screening", "Interview", "Offer"],
    firstEventDaysAgo: 45,
    stepDays: 9,
    location: TORONTO,
    arrangement: "Hybrid",
    salary: "$25/hour",
    notes: "Offer open until the end of the month.",
  },
  {
    id: "accenture-technology-strategy-s27",
    company: "Accenture",
    domain: "accenture.com",
    title: "Technology Strategy Intern",
    category: "Consulting",
    term: "Summer 2027",
    source: "LinkedIn",
    path: ["Applied", "Screening", "Assessment", "Interview", "Offer"],
    firstEventDaysAgo: 50,
    stepDays: 9,
    location: TORONTO,
    arrangement: "Hybrid",
    salary: "$28/hour",
    duration: "4 months",
    notes:
      "Four stages, and the longest process of the three offers. A summer role, so it does not compete with the winter ones.",
  },
  {
    id: "ibm-ai-automation-business-analyst-w27",
    company: "IBM",
    domain: "ibm.com",
    title: "AI & Automation Business Analyst Intern",
    category: "Information Technology",
    term: "Winter 2027",
    source: "Company website",
    path: ["Applied", "Screening", "Assessment"],
    firstEventDaysAgo: 26,
    stepDays: 13,
    location: TORONTO,
    arrangement: "Remote",
    duration: "4 months",
    notes:
      "Assessment is a written exercise: pick a manual process, describe how you would automate it and what could go wrong. 90 minutes, submitted through their portal.",
    jobDescription:
      "Join a team helping clients identify processes worth automating and prepare the business case for doing so. This is a business analysis role: the reasoning about which processes to change matters more than the tooling.\n\nWhat you will do\n- Map manual processes and quantify the effort they consume\n- Prepare the benefits case for candidate automations\n- Document exception paths and the controls a change would need\n- Present findings to the client's process owners",
    nextAction: {
      text: "Submit the IBM written assessment",
      inDays: 4,
    },
  },
  {
    id: "deloitte-risk-advisory-w27",
    company: "Deloitte",
    domain: "deloitte.com",
    title: "Risk Advisory Intern",
    category: "Consulting",
    term: "Winter 2027",
    source: "LinkedIn",
    path: ["Applied", "Screening"],
    firstEventDaysAgo: 22,
    stepDays: 8,
    location: TORONTO,
  },
  {
    id: "kpmg-business-analyst-w27",
    company: "KPMG",
    domain: "kpmg.com",
    title: "Business Analyst Intern",
    category: "Business Analysis",
    term: "Winter 2027",
    source: "University job board",
    path: ["Applied"],
    firstEventDaysAgo: 20,
    location: TORONTO,
  },
  {
    id: "ey-consulting-w27",
    company: "EY",
    domain: "ey.com",
    title: "Consulting Intern",
    category: "Consulting",
    term: "Winter 2027",
    source: "Company website",
    path: ["Applied"],
    firstEventDaysAgo: 24,
    location: TORONTO,
    arrangement: "Hybrid",
  },
  {
    id: "pwc-cybersecurity-business-analyst-w27",
    company: "PwC",
    domain: "pwc.com",
    title: "Cybersecurity Business Analyst Intern",
    category: "Information Technology",
    term: "Winter 2027",
    source: "Recruiter",
    path: ["Applied", "Screening"],
    firstEventDaysAgo: 28,
    stepDays: 9,
    location: TORONTO,
    arrangement: "Hybrid",
  },
  {
    id: "bmo-digital-marketing-w27",
    company: "BMO",
    domain: "bmo.com",
    title: "Digital Marketing Intern",
    category: "Marketing",
    term: "Winter 2027",
    source: "LinkedIn",
    path: ["Applied", "Rejected"],
    firstEventDaysAgo: 42,
    stepDays: 13,
  },
  {
    id: "scotiabank-risk-analyst-w27",
    company: "Scotiabank",
    domain: "scotiabank.com",
    title: "Risk Analyst Intern",
    category: "Finance",
    term: "Winter 2027",
    source: "Company website",
    path: ["Applied", "Assessment"],
    firstEventDaysAgo: 25,
    stepDays: 9,
    location: TORONTO,
    nextAction: { text: "Complete the Scotiabank numerical assessment", inDays: 5 },
  },
  {
    id: "cibc-product-operations-w27",
    company: "CIBC",
    domain: "cibc.com",
    title: "Product Operations Intern",
    category: "Product Management",
    term: "Winter 2027",
    source: "Networking event",
    path: ["Applied"],
    firstEventDaysAgo: 17,
    location: TORONTO,
  },
  {
    id: "nbc-project-management-w27",
    company: "National Bank of Canada",
    domain: "nbc.ca",
    title: "Project Management Intern",
    category: "Project Management",
    term: "Winter 2027",
    source: "LinkedIn",
    path: ["Applied", "Rejected"],
    firstEventDaysAgo: 35,
    stepDays: 13,
    location: "Montréal, QC",
  },
  {
    id: "ibm-marketing-w27",
    company: "IBM",
    domain: "ibm.com",
    title: "Marketing Intern",
    category: "Marketing",
    term: "Winter 2027",
    source: "Indeed",
    path: ["Applied", "Rejected"],
    firstEventDaysAgo: 39,
    stepDays: 12,
    // Rejected, read, and tidied away. Still part of the funnel.
    archivedDaysAgo: 15,
  },
  {
    id: "shopify-revenue-operations-w27",
    company: "Shopify",
    domain: "shopify.com",
    title: "Revenue Operations Intern",
    category: "Revenue Operations",
    term: "Winter 2027",
    source: "LinkedIn",
    path: ["Applied", "Screening"],
    firstEventDaysAgo: 19,
    stepDays: 7,
    arrangement: "Remote",
  },
  {
    id: "canadian-tire-procurement-analyst-w27",
    company: "Canadian Tire",
    domain: "canadiantire.ca",
    title: "Procurement Analyst Intern",
    category: "Strategy and Operations",
    term: "Winter 2027",
    source: "Company website",
    path: ["Applied", "Screening", "Interview"],
    firstEventDaysAgo: 29,
    stepDays: 14,
    location: TORONTO,
    nextAction: { text: "Canadian Tire interview", inDays: 6 },
  },
  {
    id: "rogers-customer-strategy-w27",
    company: "Rogers",
    domain: "rogers.com",
    title: "Customer Strategy Intern",
    category: "Strategy and Operations",
    term: "Winter 2027",
    source: "University job board",
    path: ["Applied", "Withdrawn"],
    firstEventDaysAgo: 37,
    stepDays: 14,
    notes: "Withdrew before the screening call.",
  },
  {
    id: "td-marketing-strategy-w27",
    company: "TD",
    domain: "td.com",
    title: "Marketing Strategy Intern",
    category: "Marketing",
    term: "Winter 2027",
    source: "Company website",
    path: ["Applied", "Screening", "Interview"],
    firstEventDaysAgo: 30,
    stepDays: 9,
    location: TORONTO,
    arrangement: "Hybrid",
  },
  {
    id: "accenture-business-process-improvement-w27",
    company: "Accenture",
    domain: "accenture.com",
    title: "Business Process Improvement Intern",
    category: "Consulting",
    term: "Winter 2027",
    source: "Referral",
    path: ["Applied"],
    firstEventDaysAgo: 11,
    location: TORONTO,
  },
  {
    id: "rbc-strategy-w27",
    company: "RBC",
    domain: "rbc.com",
    title: "Strategy Intern",
    category: "Strategy and Operations",
    term: "Winter 2027",
    source: "Networking event",
    path: ["Interested", "Preparing"],
    firstEventDaysAgo: 12,
    stepDays: 5,
    deadlineInDays: 6,
    location: TORONTO,
    notes: "Met the team at the fall networking night. Tailoring the cover letter.",
  },

  // -------------------------------------------------------------- Summer 2027
  {
    id: "deloitte-human-capital-s27",
    company: "Deloitte",
    domain: "deloitte.com",
    title: "Human Capital Consulting Intern",
    category: "Human Resources",
    term: "Summer 2027",
    source: "LinkedIn",
    path: ["Applied"],
    firstEventDaysAgo: 9,
    location: TORONTO,
  },
  {
    id: "kpmg-deal-advisory-s27",
    company: "KPMG",
    domain: "kpmg.com",
    title: "Deal Advisory Intern",
    category: "Finance",
    term: "Summer 2027",
    source: "Company website",
    path: ["Applied", "Screening", "Assessment"],
    firstEventDaysAgo: 22,
    stepDays: 7,
    location: TORONTO,
    arrangement: "Hybrid",
  },
  {
    id: "ey-technology-consulting-s27",
    company: "EY",
    domain: "ey.com",
    title: "Technology Consulting Intern",
    category: "Consulting",
    term: "Summer 2027",
    source: "LinkedIn",
    path: ["Applied", "Screening"],
    firstEventDaysAgo: 16,
    stepDays: 7,
    location: TORONTO,
  },
  {
    id: "pwc-finance-s27",
    company: "PwC",
    domain: "pwc.com",
    title: "Finance Intern",
    category: "Finance",
    term: "Summer 2027",
    source: "University job board",
    path: ["Applied"],
    firstEventDaysAgo: 6,
    location: TORONTO,
  },
  {
    id: "ibm-business-transformation-s27",
    company: "IBM",
    domain: "ibm.com",
    title: "Business Transformation Intern",
    category: "Consulting",
    term: "Summer 2027",
    source: "Company website",
    path: ["Applied", "Screening", "Interview"],
    firstEventDaysAgo: 24,
    stepDays: 8,
    location: TORONTO,
    arrangement: "Hybrid",
  },
  {
    id: "rbc-business-intelligence-analyst-s27",
    company: "RBC",
    domain: "rbc.com",
    title: "Business Intelligence Analyst Intern",
    category: "Data and Analytics",
    term: "Summer 2027",
    source: "LinkedIn",
    path: ["Applied"],
    firstEventDaysAgo: 0,
    location: TORONTO,
  },
  {
    id: "td-product-operations-s27",
    company: "TD",
    domain: "td.com",
    title: "Product Operations Intern",
    category: "Product Management",
    term: "Summer 2027",
    source: "Referral",
    path: ["Applied", "Screening"],
    firstEventDaysAgo: 14,
    stepDays: 6,
    location: TORONTO,
    arrangement: "Hybrid",
  },
  {
    id: "bmo-human-resources-s27",
    company: "BMO",
    domain: "bmo.com",
    title: "Human Resources Intern",
    category: "Human Resources",
    term: "Summer 2027",
    source: "Indeed",
    path: ["Applied", "Rejected"],
    firstEventDaysAgo: 33,
    stepDays: 11,
  },
  {
    id: "scotiabank-corporate-strategy-s27",
    company: "Scotiabank",
    domain: "scotiabank.com",
    title: "Corporate Strategy Intern",
    category: "Strategy and Operations",
    term: "Summer 2027",
    source: "Recruiter",
    path: ["Applied", "Screening", "Interview"],
    firstEventDaysAgo: 27,
    stepDays: 9,
    location: TORONTO,
    arrangement: "Hybrid",
    notes: "Recruiter reached out on LinkedIn first. Interview was conversational.",
  },
  {
    id: "cibc-growth-marketing-s27",
    company: "CIBC",
    domain: "cibc.com",
    title: "Growth Marketing Intern",
    category: "Marketing",
    term: "Summer 2027",
    source: "LinkedIn",
    path: ["Applied", "Screening", "Assessment"],
    firstEventDaysAgo: 21,
    stepDays: 7,
    location: TORONTO,
  },
  {
    id: "air-canada-business-analyst-s27",
    company: "Air Canada",
    domain: "aircanada.com",
    title: "Business Analyst Intern",
    category: "Business Analysis",
    term: "Summer 2027",
    source: "Company website",
    path: ["Applied"],
    firstEventDaysAgo: 1,
    location: "Montréal, QC",
  },
  {
    id: "bell-marketing-operations-s27",
    company: "Bell",
    domain: "bell.ca",
    title: "Marketing Operations Intern",
    category: "Marketing Operations",
    term: "Summer 2027",
    source: "LinkedIn",
    path: ["Applied", "Assessment"],
    firstEventDaysAgo: 18,
    stepDays: 8,
    location: "Montréal, QC",
  },
  {
    id: "scotiabank-business-analyst-s27",
    company: "Scotiabank",
    domain: "scotiabank.com",
    title: "Business Analyst Intern",
    category: "Business Analysis",
    term: "Summer 2027",
    source: "University job board",
    path: ["Applied"],
    firstEventDaysAgo: 10,
    location: TORONTO,
  },
  {
    id: "opentext-sales-operations-s27",
    company: "OpenText",
    domain: "opentext.com",
    title: "Sales Operations Intern",
    category: "Sales",
    term: "Summer 2027",
    path: ["Interested"],
    firstEventDaysAgo: 6,
    deadlineInDays: 9,
    location: "Waterloo, ON",
  },
  {
    id: "sunlife-business-analyst-s27",
    company: "Sun Life",
    domain: "sunlife.com",
    title: "Business Analyst Intern",
    category: "Business Analysis",
    term: "Summer 2027",
    source: "University job board",
    path: ["Interested", "Preparing"],
    firstEventDaysAgo: 10,
    stepDays: 4,
    deadlineInDays: 3,
    location: TORONTO,
    notes: "Résumé tailored. Still need the cover letter.",
  },
  {
    id: "deloitte-operations-transformation-s27",
    company: "Deloitte",
    domain: "deloitte.com",
    title: "Operations Transformation Intern",
    category: "Strategy and Operations",
    term: "Summer 2027",
    source: "Referral",
    path: ["Interested"],
    firstEventDaysAgo: 5,
    deadlineInDays: 11,
    location: TORONTO,
  },
  {
    id: "manulife-project-management-s27",
    company: "Manulife",
    domain: "manulife.com",
    title: "Project Management Intern",
    category: "Project Management",
    term: "Summer 2027",
    source: "Company website",
    path: ["Interested", "Preparing"],
    firstEventDaysAgo: 8,
    stepDays: 4,
    deadlineInDays: 2,
    location: TORONTO,
  },
  {
    id: "cgi-pmo-s27",
    company: "CGI",
    domain: "cgi.com",
    title: "PMO Intern",
    category: "Project Management",
    term: "Summer 2027",
    source: "LinkedIn",
    path: ["Interested"],
    firstEventDaysAgo: 4,
    deadlineInDays: 7,
    location: "Ottawa, ON",
  },
  {
    id: "loblaw-digital-marketing-s27",
    company: "Loblaw",
    domain: "loblaw.ca",
    title: "Digital Marketing Intern",
    category: "Marketing",
    term: "Summer 2027",
    source: "Networking event",
    path: ["Interested", "Preparing"],
    firstEventDaysAgo: 7,
    stepDays: 3,
    deadlineInDays: 8,
    location: "Brampton, ON",
  },
  {
    id: "telus-business-analyst-s27",
    company: "Telus",
    domain: null,
    title: "Business Analyst Intern",
    category: "Business Analysis",
    term: "Summer 2027",
    path: ["Interested"],
    firstEventDaysAgo: 0,
  },
];
